/**
 * Integration test proving the sanitized demo database shipped at
 * `public/demo/KoboReader-demo.sqlite` (generated by
 * `scripts/build-demo-db.mjs`) is a real, working Kobo database — parsed
 * with `sql.js` and queried through the exact same `KoboDB` functions the
 * production app calls at runtime — and that it contains the expected
 * fictional book content rather than the real source library it was built
 * from.
 *
 * Unlike the other `*.integration.test.ts` files in this codebase, this one
 * is never skipped: `public/demo/KoboReader-demo.sqlite` is a committed
 * artifact (small, sanitized, safe to ship), not the developer's private
 * sample fixture, so it's always present in CI and on every checkout.
 */
import fs from 'fs'
import path from 'path'
import initSqlJs from 'sql.js'
import { checkIsKoboDB, getBookList, getChaptersWithNotes } from '@/models/KoboDB'

const DEMO_DB_PATH = path.resolve(__dirname, '../../../public/demo/KoboReader-demo.sqlite')

describe('demo database (public/demo/KoboReader-demo.sqlite integration)', () => {
  let db: import('sql.js').Database

  beforeAll(async () => {
    const SQL = await initSqlJs()
    const fileBuffer = fs.readFileSync(DEMO_DB_PATH)
    db = new SQL.Database(fileBuffer)
  })

  afterAll(() => {
    db?.close()
  })

  it('passes the app\'s own Kobo-database structural check', async () => {
    expect(await checkIsKoboDB(db)).toBe(true)
  })

  it('contains exactly the four curated fictional books, not the real source library', async () => {
    const books = await getBookList(db)

    expect(books).toHaveLength(4)

    // getBookList (src/models/KoboDB.ts) aliases the SQL column as
    // `bookTitle`, not `title` — the `title` rename happens one layer up in
    // KoboService.loadBooksWithNotes, which this test intentionally bypasses
    // to exercise the same raw KoboDB path the sibling integration tests use.
    const titles = books.map(b => b.bookTitle).sort()
    expect(titles).toEqual([
      "Alice's Adventures in Wonderland",
      'Frankenstein; or, The Modern Prometheus',
      'Pride and Prejudice',
      'The Adventures of Sherlock Holmes'
    ])

    const authors = books.map(b => b.author).sort()
    expect(authors).toEqual([
      'Arthur Conan Doyle',
      'Jane Austen',
      'Lewis Carroll',
      'Mary Shelley'
    ])
  })

  it('renders real highlights and a note for a book via getChaptersWithNotes, the same path the notes page uses', async () => {
    const books = await getBookList(db)
    const alice = books.find(b => b.bookTitle === "Alice's Adventures in Wonderland")
    expect(alice).toBeDefined()

    const chapters = await getChaptersWithNotes(db, alice!.contentId)
    const allNotes = chapters.flatMap(chapter => chapter.notes)

    expect(allNotes.length).toBeGreaterThan(0)
    expect(allNotes.some(note => note.text === 'Curiouser and curiouser!')).toBe(true)

    const noteWithAnnotation = allNotes.find(note => note.annotation)
    expect(noteWithAnnotation?.text).toBe(
      "It's no use going back to yesterday, because I was a different person then."
    )
    expect(noteWithAnnotation?.annotation).toBe(
      'This one hit different during a rough week — impermanence, but make it Wonderland.'
    )
  })
})
