#!/usr/bin/env node
/**
 * Builds the sanitized demo Kobo database shipped at `public/demo/KoboReader-demo.sqlite`.
 *
 * The real source file lives outside this repo, at
 * `../sample-kobo-folder/KoboReader.sqlite` (sibling to the project, the same
 * developer fixture used by `textGenerator.integration.test.ts`) — it is the
 * project owner's actual Kobo reading database, with his real book titles,
 * authors, highlights, and account email. This script never ships that data.
 * Instead it:
 *
 *   1. Picks a handful of real books from the source database (identified
 *      only by their opaque ContentID, which carries no personal meaning)
 *      purely to get a realistic reading-history shape (multiple books, a
 *      mix of highlight/note counts).
 *   2. Replaces every piece of human-readable content on those books —
 *      title, author, and all highlight/annotation text — with fictional
 *      public-domain book identities and real (public-domain, freely
 *      quotable) passages from those books.
 *   3. Deletes every other table's rows outright (Bookmark is entirely
 *      rebuilt from scratch; `user`, `Event`, `AnalyticsEvents`, etc. are
 *      wiped to zero rows) — none of those tables are read by the app, and
 *      several (`user`) contain the owner's real email address.
 *
 * Uses `sql.js` — the same WebAssembly SQLite library the production app
 * uses to parse Kobo databases in the browser — so the generated file is
 * guaranteed to be structurally identical to what the app already knows how
 * to read.
 *
 * Usage: `node scripts/build-demo-db.mjs`
 * Requires the source file to exist locally; skips (exit 0) otherwise, since
 * this script only needs to run when regenerating the shipped demo artifact,
 * not as part of every contributor's install or CI run.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import initSqlJs from 'sql.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Sibling folder to this repo — same convention as
// src/utils/__tests__/textGenerator.integration.test.ts
const SOURCE_DB_PATH = path.resolve(__dirname, '../../sample-kobo-folder/KoboReader.sqlite')
const OUTPUT_DB_PATH = path.resolve(__dirname, '../public/demo/KoboReader-demo.sqlite')

/**
 * Real ContentIDs of books to keep from the source database, mapped to the
 * fictional public-domain identity that replaces their real title/author.
 * ContentIDs are opaque UUIDs generated by the Kobo device — they carry no
 * personal information on their own, only the Title/Attribution columns did.
 */
const BOOK_PLAN = [
  {
    sourceContentId: '8729a8e9-1bd8-49ca-a07d-d50d04deaf6a',
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    highlights: [
      'Curiouser and curiouser!',
      "Why, sometimes I've believed as many as six impossible things before breakfast.",
      "We're all mad here.",
      "Who in the world am I? Ah, that's the great puzzle.",
      'Everything is queer today.'
    ],
    notes: [
      {
        text: "It's no use going back to yesterday, because I was a different person then.",
        annotation: 'This one hit different during a rough week — impermanence, but make it Wonderland.'
      }
    ]
  },
  {
    sourceContentId: '49dc2dd8-7711-4a02-aa02-7db61d3fe1b1',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    highlights: [
      'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.',
      'I could easily forgive his pride, if he had not mortified mine.',
      'There is a stubbornness about me that never can bear to be frightened at the will of others.',
      'In vain have I struggled. It will not do. My feelings will not be repressed.'
    ],
    notes: [
      {
        text: 'I declare after all there is no enjoyment like reading!',
        annotation: 'Same, honestly. Kindred spirit energy.'
      }
    ]
  },
  {
    sourceContentId: 'a2a89e2b-6eea-4861-b60c-50afa50f8f5c',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    highlights: [
      'It is a capital mistake to theorize before one has data.',
      'You see, but you do not observe.',
      'There is nothing more deceptive than an obvious fact.',
      'The world is full of obvious things which nobody by any chance ever observes.'
    ],
    notes: [
      {
        text: 'It is a capital mistake to theorize before one has data.',
        annotation: 'Applies to way more than detective work — good reminder for debugging too.'
      }
    ]
  },
  {
    sourceContentId: '5811c1d0-9fb7-46f3-8deb-4370f5483ae5',
    title: 'Frankenstein; or, The Modern Prometheus',
    author: 'Mary Shelley',
    highlights: [
      'Nothing is so painful to the human mind as a great and sudden change.',
      'Beware; for I am fearless, and therefore powerful.',
      'I ought to be thy Adam, but I am rather the fallen angel.',
      'Life, although it may only be an accumulation of anguish, is dear to me.'
    ],
    notes: [
      {
        text: 'Nothing is so painful to the human mind as a great and sudden change.',
        annotation: 'Felt this reading it during a big life transition.'
      }
    ]
  }
]

/**
 * All original, human-readable strings that must NOT survive anywhere in
 * the generated demo database — real book titles/authors and real highlight
 * text pulled directly from the source. Used both to sanity-check the plan
 * above (the fictional replacements must not accidentally reuse these) and,
 * far more importantly, as the assertion the whole script exists for: proof
 * that no fragment of the owner's real reading data leaked into the public
 * artifact.
 *
 * @param {import('sql.js').Database} sourceDb - The untouched source database.
 * @returns {string[]} Real title/author/highlight/annotation strings that must not appear in the output.
 */
function collectForbiddenStrings(sourceDb) {
  const forbidden = new Set()
  const sourceIds = BOOK_PLAN.map(b => `'${b.sourceContentId}'`).join(',')

  const bookRows = sourceDb.exec(`
    SELECT Title, Attribution FROM content WHERE ContentID IN (${sourceIds})
  `)
  if (bookRows.length > 0) {
    for (const row of bookRows[0].values) {
      const [title, author] = row
      if (title) forbidden.add(String(title))
      if (author) forbidden.add(String(author))
    }
  }

  const bookmarkRows = sourceDb.exec(`
    SELECT Text, Annotation FROM Bookmark WHERE VolumeID IN (${sourceIds})
  `)
  if (bookmarkRows.length > 0) {
    for (const row of bookmarkRows[0].values) {
      const [text, annotation] = row
      if (text) forbidden.add(String(text))
      if (annotation) forbidden.add(String(annotation))
    }
  }

  // The owner's real account email, present on the `user` table regardless
  // of which books were selected above.
  const userRows = sourceDb.exec('SELECT UserEmail FROM user')
  if (userRows.length > 0) {
    for (const row of userRows[0].values) {
      const [email] = row
      if (email) forbidden.add(String(email))
    }
  }

  return Array.from(forbidden).filter(s => s.length > 0)
}

/**
 * Deletes every row from every table in the database except the ones this
 * script explicitly repopulates (`content`, `Bookmark`), so no unrelated
 * table (`user`, `Event`, `AnalyticsEvents`, `Wishlist`, ...) can carry any
 * trace of the owner's real Kobo account into the shipped artifact.
 *
 * @param {import('sql.js').Database} db - The database to wipe (mutated in place).
 */
function wipeAllTables(db) {
  const tables = db.exec("SELECT name FROM sqlite_master WHERE type='table'")[0].values.map(r => r[0])
  for (const table of tables) {
    db.run(`DELETE FROM "${table}"`)
  }
}

/**
 * Rebuilds the `content` table with only the sanitized demo books and one
 * synthetic chapter row per book.
 *
 * A chapter row is required even though the demo doesn't need real chapter
 * structure: `getChaptersWithNotes` (src/models/KoboDB.ts) indexes into
 * `thisBookChapters[0]` when it needs to build its "unmatched notes" bucket,
 * which throws if a book has zero chapter rows. Giving each book exactly one
 * chapter, and pointing every fabricated highlight at that chapter's
 * ContentID, means notes render inside a normal "Chapter 1" section instead
 * of only the unmatched-notes fallback.
 *
 * @param {import('sql.js').Database} db - The database to populate (mutated in place).
 * @returns {Map<string, string>} Map of book ContentID to its single chapter's ContentID, for `buildBookmarks`.
 */
function buildContentTable(db) {
  const insertBook = db.prepare(`
    INSERT INTO content (
      ContentID, ContentType, MimeType, BookID, BookTitle, Title, Subtitle, Attribution,
      Publisher, DateCreated, DateLastRead, ReadStatus, ___PercentRead, ___UserID,
      ___FileSize, Accessibility, Series, SeriesNumber
    ) VALUES (?, '6', 'application/x-kobo-epub+zip', NULL, ?, ?, NULL, ?, 'Public Domain Press',
      '2020-01-01T00:00:00.000', '2024-06-15T09:00:00.000', 1, 42, 'demo-user', 500000, 1, NULL, NULL)
  `)
  const insertChapter = db.prepare(`
    INSERT INTO content (
      ContentID, ContentType, MimeType, BookID, BookTitle, Title, ChapterIDBookmarked,
      VolumeIndex, Depth, ___UserID
    ) VALUES (?, '899', 'application/xhtml+xml', ?, ?, 'Chapter 1', ?, 0, 1, 'demo-user')
  `)

  const chapterIdByBook = new Map()
  for (const book of BOOK_PLAN) {
    insertBook.run([book.sourceContentId, book.title, book.title, book.author])
    const chapterContentId = `${book.sourceContentId}-demo-chapter-1`
    insertChapter.run([chapterContentId, book.sourceContentId, book.title, chapterContentId])
    chapterIdByBook.set(book.sourceContentId, chapterContentId)
  }
  insertBook.free()
  insertChapter.free()
  return chapterIdByBook
}

/**
 * Rebuilds the `Bookmark` table from scratch with only fabricated
 * highlight/note rows for the demo books, each pointed at its book's
 * synthetic chapter so it renders as a normal chapter note rather than
 * falling into the "Other Highlights" unmatched bucket.
 *
 * @param {import('sql.js').Database} db - The database to populate (mutated in place).
 * @param {Map<string, string>} chapterIdByBook - Book ContentID to chapter ContentID, from `buildContentTable`.
 */
function buildBookmarkTable(db, chapterIdByBook) {
  const insert = db.prepare(`
    INSERT INTO Bookmark (
      BookmarkID, VolumeID, ContentID, StartContainerPath, StartContainerChildIndex,
      StartOffset, EndContainerPath, EndContainerChildIndex, EndOffset, Text, Annotation,
      DateCreated, ChapterProgress, Hidden, Type
    ) VALUES (?, ?, ?, ?, 0, ?, ?, 0, ?, ?, ?, ?, ?, 'false', ?)
  `)

  let sequence = 0
  for (const book of BOOK_PLAN) {
    const chapterContentId = chapterIdByBook.get(book.sourceContentId)

    const rows = [
      ...book.highlights.map(text => ({ text, annotation: null })),
      ...book.notes.map(n => ({ text: n.text, annotation: n.annotation }))
    ]

    rows.forEach((row, i) => {
      sequence += 1
      const path = `span#kobo.${sequence}.1`
      const offset = sequence * 10
      const progress = Math.min(0.95, (i + 1) / (rows.length + 1))
      const date = `2024-0${(sequence % 6) + 1}-15T10:00:00.000`
      insert.run([
        `demo-bookmark-${sequence}`,
        book.sourceContentId,
        chapterContentId,
        path,
        offset,
        path,
        offset + row.text.length,
        row.text,
        row.annotation,
        date,
        progress,
        row.annotation ? 'note' : 'highlight'
      ])
    })
  }
  insert.free()
}

async function main() {
  if (!fs.existsSync(SOURCE_DB_PATH)) {
    console.log(`Source database not found at ${SOURCE_DB_PATH} — skipping demo DB generation.`)
    return
  }

  const SQL = await initSqlJs()
  const sourceBuffer = fs.readFileSync(SOURCE_DB_PATH)
  const db = new SQL.Database(sourceBuffer)

  try {
    const forbiddenStrings = collectForbiddenStrings(db)

    wipeAllTables(db)
    const chapterIdByBook = buildContentTable(db)
    buildBookmarkTable(db, chapterIdByBook)
    db.run('VACUUM')

    const outputBuffer = Buffer.from(db.export())

    // Prove the sanitization worked before writing anything to disk: none of
    // the real titles/authors/highlights/annotations/email collected from
    // the source database may appear anywhere in the exported bytes.
    const outputText = outputBuffer.toString('latin1')
    const leaked = forbiddenStrings.filter(s => outputText.includes(s))
    if (leaked.length > 0) {
      throw new Error(
        `Sanitization check failed — ${leaked.length} original string(s) survived in the exported database: ${JSON.stringify(leaked.slice(0, 5))}`
      )
    }

    fs.mkdirSync(path.dirname(OUTPUT_DB_PATH), { recursive: true })
    fs.writeFileSync(OUTPUT_DB_PATH, outputBuffer)

    console.log(`Wrote sanitized demo database to ${OUTPUT_DB_PATH} (${outputBuffer.length} bytes).`)
    console.log(`Verified ${forbiddenStrings.length} original string(s) do not appear in the output.`)
  } finally {
    db.close()
  }
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
